version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: php-fpm

  nginx:
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www

  db:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clicks_service
      MYSQL_USER: clicks_user
      MYSQL_PASSWORD: password

  redis:
    ports:
      - "6379:6379"
