version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clicks-service-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - clicks-service
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: clicks-service-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - clicks-service
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: clicks-service-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clicks_service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: clicks_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - clicks-service

  redis:
    image: redis:alpine
    container_name: clicks-service-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - clicks-service

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

networks:
  clicks-service:
    driver: bridge
